# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/open-source/newrelic-sb-sdk/",
        "doc_host": "https://softbutterfly.gitlab.io",
        "git_url": "https://gitlab.com/softbutterfly/open-source/newrelic-sb-sdk/-/tree/master/",
        "lib_path": "src/newrelic_sb_sdk",
    },
    "syms": {
        "newrelic_sb_sdk.core.base": {
            "newrelic_sb_sdk.core.base.BaseEntity": (
                "Core/base.html#baseentity",
                "newrelic_sb_sdk/core/base.py",
            ),
            "newrelic_sb_sdk.core.base.SerializableEnum": (
                "Core/base.html#serializableenum",
                "newrelic_sb_sdk/core/base.py",
            ),
            "newrelic_sb_sdk.core.base.SerializableEnum.__repr__": (
                "Core/base.html#serializableenum.__repr__",
                "newrelic_sb_sdk/core/base.py",
            ),
            "newrelic_sb_sdk.core.base.SerializableEnum.to_json": (
                "Core/base.html#serializableenum.to_json",
                "newrelic_sb_sdk/core/base.py",
            ),
        },
        "newrelic_sb_sdk.core.encoders": {
            "newrelic_sb_sdk.core.encoders.EntityEncoder": (
                "Core/encoders.html#entityencoder",
                "newrelic_sb_sdk/core/encoders.py",
            ),
            "newrelic_sb_sdk.core.encoders.EntityEncoder.default": (
                "Core/encoders.html#entityencoder.default",
                "newrelic_sb_sdk/core/encoders.py",
            ),
        },
        "newrelic_sb_sdk.core.mixins": {
            "newrelic_sb_sdk.core.mixins.GQLMixin": (
                "Core/mixins.html#gqlmixin",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.GQLMixin.get_gql_input": (
                "Core/mixins.html#gqlmixin.get_gql_input",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.GQLMixin.gql": (
                "Core/mixins.html#gqlmixin.gql",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin": (
                "Core/mixins.html#jsonmixin",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin._dumps_json": (
                "Core/mixins.html#jsonmixin._dumps_json",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin._load_json": (
                "Core/mixins.html#jsonmixin._load_json",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin._process_properties": (
                "Core/mixins.html#jsonmixin._process_properties",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin._process_property": (
                "Core/mixins.html#jsonmixin._process_property",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin.from_json": (
                "Core/mixins.html#jsonmixin.from_json",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.JSONMixin.to_json": (
                "Core/mixins.html#jsonmixin.to_json",
                "newrelic_sb_sdk/core/mixins.py",
            ),
            "newrelic_sb_sdk.core.mixins.SerializableMixin": (
                "Core/mixins.html#serializablemixin",
                "newrelic_sb_sdk/core/mixins.py",
            ),
        },
        "newrelic_sb_sdk.core.query": {
            "newrelic_sb_sdk.core.query.build_query": (
                "Utils/query.html#build_query",
                "newrelic_sb_sdk/core/query.py",
            )
        },
        "newrelic_sb_sdk.core.response": {
            "newrelic_sb_sdk.core.response.get_response_data": (
                "Utils/response.html#get_response_data",
                "newrelic_sb_sdk/core/response.py",
            ),
            "newrelic_sb_sdk.core.response.print_response": (
                "Utils/response.html#print_response",
                "newrelic_sb_sdk/core/response.py",
            ),
        },
        "newrelic_sb_sdk.utils.text": {
            "newrelic_sb_sdk.utils.text.camel2snake": (
                "Utils/text.html#camel2snake",
                "newrelic_sb_sdk/utils/text.py",
            ),
            "newrelic_sb_sdk.utils.text.camelize_keys": (
                "Utils/text.html#camelize_keys",
                "newrelic_sb_sdk/utils/text.py",
            ),
            "newrelic_sb_sdk.utils.text.snake2camel": (
                "Utils/text.html#snake2camel",
                "newrelic_sb_sdk/utils/text.py",
            ),
            "newrelic_sb_sdk.utils.text.snakeize_keys": (
                "Utils/text.html#snakeize_keys",
                "newrelic_sb_sdk/utils/text.py",
            ),
        },
    },
}
